/**
 * Builders Observability — AI operation scope.
 *
 * Gives every AI request an `operation_id` identifying the application generation it belongs to,
 * so Generation Analytics can group requests EXACTLY rather than inferring boundaries.
 *
 * The ledger has had an `operation_id` column since Sprint 42, but nothing ever populated it —
 * `useGenerateText` accepted the option and no caller passed it, so the column is null on every
 * historical row. This module is the missing producer.
 *
 * Deliberately module-level rather than React state: one generation spans many roles across many
 * renders (and, for the autonomous pipeline, outlives the component that started it), exactly
 * like the `runningProjectIds` set in useAutoEngineeringPipeline.ts that this mirrors.
 *
 * Purely additive instrumentation. Nothing here can fail a generation: `resolveOperationId()`
 * always returns a usable id, and the id is only ever attached to a usage row.
 */

/** Active scopes, keyed by project id. An entry exists only while that project has a run in flight. */
const activeScopes = new Map<string, string>();

let counter = 0;

/**
 * Ids are `gen_<time>_<counter>_<random>`. The counter disambiguates two runs started inside the
 * same millisecond; the random suffix keeps ids from colliding across browser tabs, which write
 * to the same ledger under the same user.
 */
function mintOperationId(): string {
  counter += 1;
  return `gen_${Date.now().toString(36)}_${counter.toString(36)}_${Math.random().toString(36).slice(2, 8)}`;
}

/**
 * Opens a scope for `projectId` and returns its id. An already-open scope is returned unchanged
 * rather than replaced — a pipeline that resumes mid-run (Sprint 46's resume path re-enters the
 * same effect) must stay part of the same generation, not start a second one.
 */
export function beginAiOperationScope(projectId: string): string {
  const existing = activeScopes.get(projectId);

  if (existing) {
    return existing;
  }

  const operationId = mintOperationId();
  activeScopes.set(projectId, operationId);

  return operationId;
}

/** Closes the scope. Safe to call when none is open. */
export function endAiOperationScope(projectId: string): void {
  activeScopes.delete(projectId);
}

export function currentAiOperationScope(projectId: string): string | undefined {
  return activeScopes.get(projectId);
}

/**
 * The id a call site should attach to a usage row.
 *
 * Inside a pipeline run this is that run's id, so every role lands in one generation. Outside one
 * — a single role regenerated by hand from a draft panel — it mints a standalone id, so that call
 * is still a (one-request) generation rather than an ungrouped orphan. That is why this never
 * returns undefined: an unattributed row would fall back to inferred grouping forever.
 */
export function resolveOperationId(projectId: string): string {
  return activeScopes.get(projectId) ?? mintOperationId();
}

/** Test seam only — never called by application code. */
export function resetAiOperationScopes(): void {
  activeScopes.clear();
}
