import type { ProjectTask } from './taskEngine';

/**
 * Project Task Engine — registry.
 *
 * The raw data, one task list per blueprint id (same ids as
 * app/lib/blueprints/registry.ts's PROJECT_BLUEPRINTS). Intentionally NOT
 * exported from anywhere outside this module — everything reads task data
 * through `projectTaskEngine` (taskEngine.ts), never this object directly,
 * matching the blueprint registry/engine split in app/lib/blueprints/.
 *
 * `nextTasks` is omitted here on purpose: it is the reverse of `dependsOn`
 * and is computed once by taskEngine.ts so it never has to be kept in sync
 * by hand across every task below.
 *
 * Every `roadmapKey` must match a `RoadmapItem.key` already defined on the
 * corresponding blueprint in app/lib/blueprints/registry.ts — that's what
 * lets task status derive from the project's existing roadmap completion
 * data (Project.roadmapStatus) instead of introducing a second, parallel
 * source of truth. Several tasks may share one roadmapKey (e.g. "Homepage"
 * and "Hero" both roll up under the "homepage" roadmap step) — the Task
 * Engine is a more granular execution breakdown underneath each roadmap
 * step, not a replacement for it.
 */

export type TaskDefinition = Omit<ProjectTask, 'nextTasks'>;

export const TASK_REGISTRY: Record<string, TaskDefinition[]> = {
  'blank-project': [
    {
      id: 'requirements',
      roadmapKey: 'requirements',
      title: 'Requirements',
      description: 'Capture what this project should do before building anything.',
      category: 'planning',
      dependsOn: [],
      requiredKnowledge: ['projectVision'],
      outputType: 'Requirements Summary',
      aiAction: 'summarize-requirements',
      estimatedMinutes: 15,
    },
    {
      id: 'planning',
      roadmapKey: 'planning',
      title: 'Planning',
      description: 'Pick a stack and approach based on the captured requirements.',
      category: 'planning',
      dependsOn: ['requirements'],
      requiredKnowledge: ['projectVision', 'technicalPreferences'],
      outputType: 'Technical Plan',
      aiAction: 'draft-technical-plan',
      estimatedMinutes: 20,
    },
    {
      id: 'deployment',
      roadmapKey: 'deployment',
      title: 'Deployment',
      description: 'Deploy the project once it is ready.',
      category: 'deployment',
      dependsOn: ['planning'],
      requiredKnowledge: [],
      outputType: 'Deployment Config',
      aiAction: 'generate-deployment-config',
      estimatedMinutes: 15,
    },
  ],

  'business-website': [
    {
      id: 'requirements',
      roadmapKey: 'requirements',
      title: 'Requirements',
      description: 'Define business requirements for the website.',
      category: 'planning',
      dependsOn: [],
      requiredKnowledge: ['projectVision', 'targetUsers', 'industry'],
      outputType: 'Requirements Summary',
      aiAction: 'summarize-requirements',
      estimatedMinutes: 20,
    },
    {
      id: 'homepage',
      roadmapKey: 'homepage',
      title: 'Homepage',
      description: 'Design and build the homepage layout.',
      category: 'frontend',
      dependsOn: ['requirements'],
      requiredKnowledge: ['coreFeatures', 'brandTone'],
      outputType: 'Page Layout',
      aiAction: 'generate-homepage-layout',
      estimatedMinutes: 45,
    },
    {
      id: 'navigation',
      roadmapKey: 'navigation',
      title: 'Navigation',
      description: 'Set up site navigation and structure.',
      category: 'frontend',
      dependsOn: ['requirements'],
      requiredKnowledge: ['pagesOrScreens'],
      outputType: 'Navigation Structure',
      aiAction: 'generate-navigation',
      estimatedMinutes: 25,
    },
    {
      id: 'hero',
      roadmapKey: 'homepage',
      title: 'Hero',
      description: 'Design the homepage hero section.',
      category: 'design',
      dependsOn: ['homepage'],
      requiredKnowledge: ['brandTone', 'designPreferences'],
      outputType: 'UI Component',
      aiAction: 'generate-hero-section',
      estimatedMinutes: 20,
    },
    {
      id: 'about',
      roadmapKey: 'about',
      title: 'About',
      description: 'Add an About section.',
      category: 'frontend',
      dependsOn: ['navigation'],
      requiredKnowledge: ['projectVision', 'industry'],
      outputType: 'Page Section',
      aiAction: 'generate-about-section',
      estimatedMinutes: 20,
    },
    {
      id: 'services',
      roadmapKey: 'services',
      title: 'Services',
      description: 'Add a services section.',
      category: 'frontend',
      dependsOn: ['navigation'],
      requiredKnowledge: ['coreFeatures'],
      outputType: 'Page Section',
      aiAction: 'generate-services-section',
      estimatedMinutes: 30,
    },
    {
      id: 'contact',
      roadmapKey: 'contact',
      title: 'Contact',
      description: 'Add a contact section and form.',
      category: 'frontend',
      dependsOn: ['navigation'],
      requiredKnowledge: ['integrations', 'location'],
      outputType: 'Contact Form',
      aiAction: 'generate-contact-section',
      estimatedMinutes: 20,
    },
    {
      id: 'seo',
      roadmapKey: 'seo',
      title: 'SEO',
      description: 'Add SEO metadata.',
      category: 'integration',
      dependsOn: ['homepage', 'about', 'services', 'contact'],
      requiredKnowledge: ['industry', 'targetUsers'],
      outputType: 'SEO Metadata',
      aiAction: 'generate-seo-metadata',
      estimatedMinutes: 15,
    },
    {
      id: 'responsive',
      roadmapKey: 'responsive-design',
      title: 'Responsive Design',
      description: 'Ensure the site works on all screen sizes.',
      category: 'design',
      dependsOn: ['homepage', 'navigation', 'about', 'services', 'contact'],
      requiredKnowledge: [],
      outputType: 'Responsive Styles',
      aiAction: 'generate-responsive-styles',
      estimatedMinutes: 25,
    },
    {
      id: 'deployment',
      roadmapKey: 'deployment',
      title: 'Deployment',
      description: 'Deploy the website.',
      category: 'deployment',
      dependsOn: ['seo', 'responsive'],
      requiredKnowledge: [],
      outputType: 'Deployment Config',
      aiAction: 'generate-deployment-config',
      estimatedMinutes: 20,
    },
  ],

  'localshop-india': [
    {
      id: 'requirements',
      roadmapKey: 'requirements',
      title: 'Requirements',
      description: 'Define business requirements.',
      category: 'planning',
      dependsOn: [],
      requiredKnowledge: ['projectVision', 'targetUsers', 'industry'],
      outputType: 'Requirements Summary',
      aiAction: 'summarize-requirements',
      estimatedMinutes: 25,
    },
    {
      id: 'categories',
      roadmapKey: 'product-catalog',
      title: 'Categories',
      description: 'Define product categories.',
      category: 'database',
      dependsOn: ['requirements'],
      requiredKnowledge: ['coreFeatures'],
      outputType: 'Database Schema',
      aiAction: 'generate-category-schema',
      estimatedMinutes: 20,
    },
    {
      id: 'products',
      roadmapKey: 'product-catalog',
      title: 'Products',
      description: 'Build the product catalog.',
      category: 'database',
      dependsOn: ['categories'],
      requiredKnowledge: ['coreFeatures'],
      outputType: 'Database Schema',
      aiAction: 'generate-product-schema',
      estimatedMinutes: 35,
    },
    {
      id: 'cart',
      roadmapKey: 'shopping-cart',
      title: 'Cart',
      description: 'Add cart functionality.',
      category: 'frontend',
      dependsOn: ['products'],
      requiredKnowledge: [],
      outputType: 'UI Component',
      aiAction: 'generate-cart-ui',
      estimatedMinutes: 30,
    },
    {
      id: 'checkout',
      roadmapKey: 'checkout',
      title: 'Checkout',
      description: 'Build the checkout flow.',
      category: 'frontend',
      dependsOn: ['cart'],
      requiredKnowledge: ['userRoles'],
      outputType: 'Checkout Flow',
      aiAction: 'generate-checkout-flow',
      estimatedMinutes: 40,
    },
    {
      id: 'gst',
      roadmapKey: 'razorpay-upi-payments',
      title: 'GST',
      description: 'Handle GST and invoice compliance.',
      category: 'integration',
      dependsOn: ['checkout'],
      requiredKnowledge: ['complianceNeeds'],
      outputType: 'Compliance Config',
      aiAction: 'generate-gst-compliance',
      estimatedMinutes: 25,
    },
    {
      id: 'payments',
      roadmapKey: 'razorpay-upi-payments',
      title: 'Payments',
      description: 'Integrate Razorpay and UPI payments.',
      category: 'integration',
      dependsOn: ['checkout'],
      requiredKnowledge: ['paymentNeeds'],
      outputType: 'Payment Integration',
      aiAction: 'generate-payment-integration',
      estimatedMinutes: 35,
    },
    {
      id: 'shipping',
      roadmapKey: 'order-management',
      title: 'Shipping',
      description: 'Plan shipping and fulfillment.',
      category: 'integration',
      dependsOn: ['checkout'],
      requiredKnowledge: ['shippingNeeds'],
      outputType: 'Shipping Config',
      aiAction: 'generate-shipping-config',
      estimatedMinutes: 25,
    },
    {
      id: 'orders',
      roadmapKey: 'order-management',
      title: 'Orders',
      description: 'Plan order management and fulfillment.',
      category: 'backend',
      dependsOn: ['payments', 'shipping'],
      requiredKnowledge: [],
      outputType: 'Order Management API',
      aiAction: 'generate-order-management',
      estimatedMinutes: 35,
    },
    {
      id: 'admin',
      roadmapKey: 'vendor-model',
      title: 'Admin',
      description: 'Build the admin/vendor dashboard.',
      category: 'frontend',
      dependsOn: ['orders'],
      requiredKnowledge: ['userRoles'],
      outputType: 'Admin Dashboard',
      aiAction: 'generate-admin-dashboard',
      estimatedMinutes: 40,
    },
    {
      id: 'deployment',
      roadmapKey: 'deployment',
      title: 'Deployment',
      description: 'Deploy the storefront.',
      category: 'deployment',
      dependsOn: ['admin', 'gst'],
      requiredKnowledge: [],
      outputType: 'Deployment Config',
      aiAction: 'generate-deployment-config',
      estimatedMinutes: 20,
    },
  ],

  'shopify-app': [
    {
      id: 'requirements',
      roadmapKey: 'requirements',
      title: 'Requirements',
      description: 'Define business requirements.',
      category: 'planning',
      dependsOn: [],
      requiredKnowledge: ['projectVision', 'targetUsers'],
      outputType: 'Requirements Summary',
      aiAction: 'summarize-requirements',
      estimatedMinutes: 20,
    },
    {
      id: 'app-structure',
      roadmapKey: 'app-structure',
      title: 'App Structure',
      description: 'Register the app and define its structure.',
      category: 'planning',
      dependsOn: ['requirements'],
      requiredKnowledge: ['technicalPreferences'],
      outputType: 'App Scaffold',
      aiAction: 'generate-app-structure',
      estimatedMinutes: 30,
    },
    {
      id: 'authentication',
      roadmapKey: 'authentication',
      title: 'Authentication',
      description: 'Set up the Shopify OAuth flow.',
      category: 'backend',
      dependsOn: ['app-structure'],
      requiredKnowledge: [],
      outputType: 'OAuth Flow',
      aiAction: 'generate-oauth-flow',
      estimatedMinutes: 35,
    },
    {
      id: 'polaris-ui',
      roadmapKey: 'polaris-ui',
      title: 'Polaris UI',
      description: 'Build the UI with Shopify Polaris.',
      category: 'frontend',
      dependsOn: ['app-structure'],
      requiredKnowledge: ['coreFeatures'],
      outputType: 'UI Components',
      aiAction: 'generate-polaris-ui',
      estimatedMinutes: 40,
    },
    {
      id: 'app-bridge',
      roadmapKey: 'app-bridge',
      title: 'App Bridge',
      description: 'Integrate Shopify App Bridge.',
      category: 'integration',
      dependsOn: ['polaris-ui'],
      requiredKnowledge: [],
      outputType: 'Integration Config',
      aiAction: 'generate-app-bridge-integration',
      estimatedMinutes: 25,
    },
    {
      id: 'webhooks',
      roadmapKey: 'webhooks',
      title: 'Webhooks',
      description: 'Define required Shopify webhooks.',
      category: 'backend',
      dependsOn: ['authentication'],
      requiredKnowledge: ['integrations'],
      outputType: 'Webhook Handlers',
      aiAction: 'generate-webhook-handlers',
      estimatedMinutes: 30,
    },
    {
      id: 'billing',
      roadmapKey: 'billing',
      title: 'Billing',
      description: 'Plan billing via the Shopify Billing API.',
      category: 'integration',
      dependsOn: ['authentication'],
      requiredKnowledge: ['paymentNeeds'],
      outputType: 'Billing Integration',
      aiAction: 'generate-billing-integration',
      estimatedMinutes: 30,
    },
    {
      id: 'testing',
      roadmapKey: 'testing',
      title: 'Testing',
      description: 'Test the app against a development store.',
      category: 'integration',
      dependsOn: ['app-bridge', 'webhooks', 'billing'],
      requiredKnowledge: [],
      outputType: 'Test Plan',
      aiAction: 'generate-test-plan',
      estimatedMinutes: 25,
    },
    {
      id: 'deployment',
      roadmapKey: 'deployment',
      title: 'Deployment',
      description: 'Submit and deploy the app.',
      category: 'deployment',
      dependsOn: ['testing'],
      requiredKnowledge: [],
      outputType: 'Deployment Config',
      aiAction: 'generate-deployment-config',
      estimatedMinutes: 15,
    },
  ],

  'ai-agent': [
    {
      id: 'requirements',
      roadmapKey: 'requirements',
      title: 'Requirements',
      description: 'Define business requirements.',
      category: 'planning',
      dependsOn: [],
      requiredKnowledge: ['projectVision', 'targetUsers'],
      outputType: 'Requirements Summary',
      aiAction: 'summarize-requirements',
      estimatedMinutes: 20,
    },
    {
      id: 'agent-goal',
      roadmapKey: 'architecture',
      title: 'Agent Goal',
      description: "Define the agent's goal, tools, and architecture.",
      category: 'planning',
      dependsOn: ['requirements'],
      requiredKnowledge: ['projectVision', 'notes'],
      outputType: 'Agent Architecture Spec',
      aiAction: 'generate-agent-architecture',
      estimatedMinutes: 30,
    },
    {
      id: 'memory',
      roadmapKey: 'memory',
      title: 'Memory',
      description: 'Design agent memory and state.',
      category: 'backend',
      dependsOn: ['agent-goal'],
      requiredKnowledge: [],
      outputType: 'Memory Store Config',
      aiAction: 'generate-memory-config',
      estimatedMinutes: 30,
    },
    {
      id: 'tools',
      roadmapKey: 'tool-calling',
      title: 'Tools',
      description: 'Define and wire up tool calling.',
      category: 'backend',
      dependsOn: ['agent-goal'],
      requiredKnowledge: ['coreFeatures', 'integrations'],
      outputType: 'Tool Definitions',
      aiAction: 'generate-tool-definitions',
      estimatedMinutes: 35,
    },
    {
      id: 'workflow',
      roadmapKey: 'mcp',
      title: 'Workflow',
      description: 'Design the agent workflow and MCP connections.',
      category: 'integration',
      dependsOn: ['tools', 'memory'],
      requiredKnowledge: ['integrations'],
      outputType: 'Workflow Spec',
      aiAction: 'generate-workflow-spec',
      estimatedMinutes: 30,
    },
    {
      id: 'prompt',
      roadmapKey: 'architecture',
      title: 'Prompt',
      description: "Write the agent's system prompt.",
      category: 'backend',
      dependsOn: ['agent-goal'],
      requiredKnowledge: ['notes', 'brandTone'],
      outputType: 'Prompt Specification',
      aiAction: 'draft-system-prompt',
      estimatedMinutes: 25,
    },
    {
      id: 'testing',
      roadmapKey: 'testing',
      title: 'Testing',
      description: 'Test agent behavior end-to-end.',
      category: 'integration',
      dependsOn: ['workflow', 'prompt'],
      requiredKnowledge: [],
      outputType: 'Test Plan',
      aiAction: 'generate-test-plan',
      estimatedMinutes: 25,
    },
    {
      id: 'deployment',
      roadmapKey: 'deployment',
      title: 'Deployment',
      description: 'Deploy the agent.',
      category: 'deployment',
      dependsOn: ['testing'],
      requiredKnowledge: [],
      outputType: 'Deployment Config',
      aiAction: 'generate-deployment-config',
      estimatedMinutes: 15,
    },
  ],

  'saas-starter': [
    {
      id: 'requirements',
      roadmapKey: 'requirements',
      title: 'Requirements',
      description: 'Define business requirements.',
      category: 'planning',
      dependsOn: [],
      requiredKnowledge: ['projectVision', 'targetUsers'],
      outputType: 'Requirements Summary',
      aiAction: 'summarize-requirements',
      estimatedMinutes: 20,
    },
    {
      id: 'pricing-plans',
      roadmapKey: 'pricing-plans',
      title: 'Pricing Plans',
      description: 'Define subscription pricing plans.',
      category: 'planning',
      dependsOn: ['requirements'],
      requiredKnowledge: ['businessModel'],
      outputType: 'Pricing Plan Spec',
      aiAction: 'generate-pricing-plans',
      estimatedMinutes: 25,
    },
    {
      id: 'authentication',
      roadmapKey: 'authentication',
      title: 'Authentication',
      description: 'Set up user authentication.',
      category: 'backend',
      dependsOn: ['requirements'],
      requiredKnowledge: ['userRoles'],
      outputType: 'Auth Flow',
      aiAction: 'generate-auth-flow',
      estimatedMinutes: 30,
    },
    {
      id: 'billing',
      roadmapKey: 'billing',
      title: 'Billing',
      description: 'Plan billing with Razorpay, UPI, or Cashfree.',
      category: 'integration',
      dependsOn: ['pricing-plans', 'authentication'],
      requiredKnowledge: ['paymentNeeds'],
      outputType: 'Billing Integration',
      aiAction: 'generate-billing-integration',
      estimatedMinutes: 35,
    },
    {
      id: 'onboarding',
      roadmapKey: 'onboarding',
      title: 'Onboarding',
      description: 'Design the onboarding flow.',
      category: 'frontend',
      dependsOn: ['authentication'],
      requiredKnowledge: ['coreFeatures'],
      outputType: 'Onboarding Flow',
      aiAction: 'generate-onboarding-flow',
      estimatedMinutes: 25,
    },
    {
      id: 'testing',
      roadmapKey: 'testing',
      title: 'Testing',
      description: 'Test core flows end-to-end.',
      category: 'integration',
      dependsOn: ['billing', 'onboarding'],
      requiredKnowledge: [],
      outputType: 'Test Plan',
      aiAction: 'generate-test-plan',
      estimatedMinutes: 25,
    },
    {
      id: 'deployment',
      roadmapKey: 'deployment',
      title: 'Deployment',
      description: 'Deploy the product.',
      category: 'deployment',
      dependsOn: ['testing'],
      requiredKnowledge: [],
      outputType: 'Deployment Config',
      aiAction: 'generate-deployment-config',
      estimatedMinutes: 15,
    },
  ],

  'mobile-app': [
    {
      id: 'requirements',
      roadmapKey: 'requirements',
      title: 'Requirements',
      description: 'Define business requirements.',
      category: 'planning',
      dependsOn: [],
      requiredKnowledge: ['projectVision', 'targetUsers'],
      outputType: 'Requirements Summary',
      aiAction: 'summarize-requirements',
      estimatedMinutes: 20,
    },
    {
      id: 'core-screens',
      roadmapKey: 'core-screens',
      title: 'Core Screens',
      description: "Define the app's core screens.",
      category: 'frontend',
      dependsOn: ['requirements'],
      requiredKnowledge: ['pagesOrScreens'],
      outputType: 'Screen Layouts',
      aiAction: 'generate-core-screens',
      estimatedMinutes: 40,
    },
    {
      id: 'navigation',
      roadmapKey: 'navigation',
      title: 'Navigation',
      description: 'Set up app navigation.',
      category: 'frontend',
      dependsOn: ['core-screens'],
      requiredKnowledge: [],
      outputType: 'Navigation Structure',
      aiAction: 'generate-navigation',
      estimatedMinutes: 25,
    },
    {
      id: 'authentication',
      roadmapKey: 'authentication',
      title: 'Authentication',
      description: 'Set up user authentication.',
      category: 'backend',
      dependsOn: ['core-screens'],
      requiredKnowledge: ['userRoles'],
      outputType: 'Auth Flow',
      aiAction: 'generate-auth-flow',
      estimatedMinutes: 30,
    },
    {
      id: 'push-notifications',
      roadmapKey: 'push-notifications',
      title: 'Push Notifications',
      description: 'Add push notifications.',
      category: 'integration',
      dependsOn: ['authentication'],
      requiredKnowledge: ['integrations'],
      outputType: 'Push Notification Config',
      aiAction: 'generate-push-notification-config',
      estimatedMinutes: 25,
    },
    {
      id: 'app-store-release',
      roadmapKey: 'app-store-release',
      title: 'App Store Release',
      description: 'Plan the app store release.',
      category: 'deployment',
      dependsOn: ['navigation', 'push-notifications'],
      requiredKnowledge: [],
      outputType: 'Release Checklist',
      aiAction: 'generate-release-checklist',
      estimatedMinutes: 30,
    },
    {
      id: 'deployment',
      roadmapKey: 'deployment',
      title: 'Deployment',
      description: 'Deploy/publish the app.',
      category: 'deployment',
      dependsOn: ['app-store-release'],
      requiredKnowledge: [],
      outputType: 'Deployment Config',
      aiAction: 'generate-deployment-config',
      estimatedMinutes: 15,
    },
  ],

  'marketing-website': [
    {
      id: 'requirements',
      roadmapKey: 'requirements',
      title: 'Requirements',
      description: 'Define business requirements.',
      category: 'planning',
      dependsOn: [],
      requiredKnowledge: ['projectVision', 'targetUsers'],
      outputType: 'Requirements Summary',
      aiAction: 'summarize-requirements',
      estimatedMinutes: 20,
    },
    {
      id: 'brand-sections',
      roadmapKey: 'brand-sections',
      title: 'Brand Sections',
      description: "Define the site's brand sections.",
      category: 'frontend',
      dependsOn: ['requirements'],
      requiredKnowledge: ['brandTone', 'designPreferences'],
      outputType: 'Page Sections',
      aiAction: 'generate-brand-sections',
      estimatedMinutes: 40,
    },
    {
      id: 'seo',
      roadmapKey: 'seo',
      title: 'SEO',
      description: 'Add SEO metadata.',
      category: 'integration',
      dependsOn: ['brand-sections'],
      requiredKnowledge: ['industry', 'targetUsers'],
      outputType: 'SEO Metadata',
      aiAction: 'generate-seo-metadata',
      estimatedMinutes: 15,
    },
    {
      id: 'analytics',
      roadmapKey: 'analytics',
      title: 'Analytics',
      description: 'Add analytics tracking.',
      category: 'integration',
      dependsOn: ['brand-sections'],
      requiredKnowledge: [],
      outputType: 'Analytics Config',
      aiAction: 'generate-analytics-config',
      estimatedMinutes: 15,
    },
    {
      id: 'contact-form',
      roadmapKey: 'contact-form',
      title: 'Contact Form',
      description: 'Add a contact form.',
      category: 'frontend',
      dependsOn: ['brand-sections'],
      requiredKnowledge: ['integrations', 'location'],
      outputType: 'Contact Form',
      aiAction: 'generate-contact-section',
      estimatedMinutes: 20,
    },
    {
      id: 'deployment',
      roadmapKey: 'deployment',
      title: 'Deployment',
      description: 'Deploy the website.',
      category: 'deployment',
      dependsOn: ['seo', 'analytics', 'contact-form'],
      requiredKnowledge: [],
      outputType: 'Deployment Config',
      aiAction: 'generate-deployment-config',
      estimatedMinutes: 20,
    },
  ],

  'nextjs-saas': [
    {
      id: 'requirements',
      roadmapKey: 'requirements',
      title: 'Requirements',
      description: 'Define business requirements.',
      category: 'planning',
      dependsOn: [],
      requiredKnowledge: ['projectVision', 'targetUsers'],
      outputType: 'Requirements Summary',
      aiAction: 'summarize-requirements',
      estimatedMinutes: 20,
    },
    {
      id: 'authentication',
      roadmapKey: 'authentication',
      title: 'Authentication',
      description: 'Set up user authentication.',
      category: 'backend',
      dependsOn: ['requirements'],
      requiredKnowledge: ['userRoles'],
      outputType: 'Auth Flow',
      aiAction: 'generate-auth-flow',
      estimatedMinutes: 30,
    },
    {
      id: 'billing',
      roadmapKey: 'billing',
      title: 'Billing',
      description: 'Plan billing with Razorpay/UPI.',
      category: 'integration',
      dependsOn: ['authentication'],
      requiredKnowledge: ['paymentNeeds'],
      outputType: 'Billing Integration',
      aiAction: 'generate-billing-integration',
      estimatedMinutes: 35,
    },
    {
      id: 'dashboard',
      roadmapKey: 'dashboard',
      title: 'Dashboard',
      description: 'Design the product dashboard.',
      category: 'frontend',
      dependsOn: ['authentication'],
      requiredKnowledge: ['coreFeatures'],
      outputType: 'Dashboard UI',
      aiAction: 'generate-dashboard-ui',
      estimatedMinutes: 35,
    },
    {
      id: 'testing',
      roadmapKey: 'testing',
      title: 'Testing',
      description: 'Test core flows end-to-end.',
      category: 'integration',
      dependsOn: ['billing', 'dashboard'],
      requiredKnowledge: [],
      outputType: 'Test Plan',
      aiAction: 'generate-test-plan',
      estimatedMinutes: 25,
    },
    {
      id: 'deployment',
      roadmapKey: 'deployment',
      title: 'Deployment',
      description: 'Deploy the product.',
      category: 'deployment',
      dependsOn: ['testing'],
      requiredKnowledge: [],
      outputType: 'Deployment Config',
      aiAction: 'generate-deployment-config',
      estimatedMinutes: 15,
    },
  ],
};
