import type { ChangeArea, ChangeCategory } from '~/lib/evolution/changeRequestTypes';

/**
 * Impact Model — Sprint 95, Parts 4/8/9/10.
 *
 * The structured result of comparing a Change Request against a released product baseline. Every
 * section is GROUNDED: an entry exists only because a real baseline identifier (a feature code, a
 * route path, a generated file, a schema table, an environment variable name) was matched, or
 * because the operator explicitly declared that area on the request. Nothing is invented, and
 * nothing is generated by an AI — this sprint's analysis is deterministic term matching over
 * artifacts that already exist.
 *
 * THE HONEST LIMITATION, stated in the model itself rather than hidden: term matching does not
 * understand intent. A request saying "make the booking flow faster" will match the booking
 * feature but cannot know whether that means a query index, a UI change or a caching layer. So
 * every finding carries a `confidence`, the report carries an overall confidence, and
 * `requiresHumanReview` is set whenever the analysis is anything less than a direct identifier
 * match. An Evolution Plan built on this is a starting point for engineering judgement, never a
 * substitute for it.
 */

/** How firmly a finding is established. `high` = an exact baseline identifier appeared in the request text. */
export type ImpactConfidence = 'high' | 'medium' | 'low';

/** What kind of baseline artifact a finding points at. */
export type ImpactItemKind =
  | 'feature'
  | 'route'
  | 'file'
  | 'component'
  | 'database_table'
  | 'environment_variable'
  | 'service'
  | 'api_surface'
  | 'documentation'
  | 'verification_check';

export interface ImpactItem {
  kind: ImpactItemKind;

  /** The baseline identifier itself — a feature code, a route path, a file path, a table name. */
  identifier: string;
  label: string;
  confidence: ImpactConfidence;

  /** The exact term from the request text that matched, or the declared area that produced this item. */
  evidence: string;
}

/** Part 4 — one section of the impact report. `affected: false` with a stated reason is a real result, not a gap. */
export interface ImpactSection {
  id: ImpactSectionId;
  label: string;
  affected: boolean;
  items: ImpactItem[];
  confidence: ImpactConfidence;

  /** Why this section concluded what it concluded. Always populated, including when nothing is affected. */
  detail: string;
}

export type ImpactSectionId =
  | 'business'
  | 'technical'
  | 'ui'
  | 'backend'
  | 'database'
  | 'security'
  | 'infrastructure'
  | 'testing'
  | 'deployment'
  | 'documentation';

export const IMPACT_SECTION_LABELS: Record<ImpactSectionId, string> = {
  business: 'Business Impact',
  technical: 'Technical Impact',
  ui: 'UI Impact',
  backend: 'Backend Impact',
  database: 'Database Impact',
  security: 'Security Impact',
  infrastructure: 'Infrastructure Impact',
  testing: 'Testing Impact',
  deployment: 'Deployment Impact',
  documentation: 'Documentation Impact',
};

// ── Risk (Part 8) ───────────────────────────────────────────────────────────

export type RiskLevel = 'low' | 'medium' | 'high' | 'critical';

export interface RiskFactor {
  id: string;
  label: string;

  /** What in the baseline or the request produced this factor. */
  detail: string;

  /** Contribution to the overall level. Documented weights, never a hidden score. */
  weight: number;
}

export interface RiskAssessment {
  level: RiskLevel;
  score: number;
  factors: RiskFactor[];

  /** A sentence a human can check the reasoning against. */
  reasoning: string;
}

// ── Complexity (Part 9) ─────────────────────────────────────────────────────

export type ComplexityLevel = 'very_small' | 'small' | 'medium' | 'large' | 'very_large';

export interface ComplexityFactor {
  id: string;
  label: string;
  detail: string;
  weight: number;
}

export interface ComplexityAssessment {
  level: ComplexityLevel;
  score: number;
  factors: ComplexityFactor[];
  reasoning: string;
}

// ── Engineering roles (Part 10) ─────────────────────────────────────────────

export type EngineeringRole =
  | 'business_analyst'
  | 'product_owner'
  | 'solution_architect'
  | 'database_engineer'
  | 'backend_engineer'
  | 'frontend_engineer'
  | 'ui_ux'
  | 'qa'
  | 'devops';

export const ENGINEERING_ROLE_LABELS: Record<EngineeringRole, string> = {
  business_analyst: 'Business Analyst',
  product_owner: 'Product Owner',
  solution_architect: 'Solution Architect',
  database_engineer: 'Database Engineer',
  backend_engineer: 'Backend Engineer',
  frontend_engineer: 'Frontend Engineer',
  ui_ux: 'UI/UX',
  qa: 'QA',
  devops: 'DevOps',
};

export interface RoleInvolvement {
  role: EngineeringRole;

  /** Why this role is involved. Only affected roles appear at all (Part 10). */
  reason: string;
}

// ── Classification (Part 5) ─────────────────────────────────────────────────

export interface ChangeClassification {
  category: ChangeCategory;

  /** `declared` — the operator chose it. `inferred` — derived from the request text and matched breadth. */
  source: 'declared' | 'inferred';
  confidence: ImpactConfidence;
  reasoning: string;

  /** Other categories the signals also pointed at, so a human can see what was close. */
  alternatives: ChangeCategory[];
}

// ── The report ──────────────────────────────────────────────────────────────

export interface ImpactAnalysis {
  /** Which release this was analysed against — never a deployment (Part 7). */
  releaseId?: string;
  releaseVersion?: string;
  baselineCapturedAt: string;
  analysedAt: string;

  classification: ChangeClassification;
  sections: ImpactSection[];

  /** Baseline areas with no finding at all — the "what can remain untouched" half of the question. */
  unaffectedAreas: Array<{ area: ChangeArea; detail: string }>;

  risk: RiskAssessment;
  complexity: ComplexityAssessment;
  roles: RoleInvolvement[];

  /** Grounded dependency notes, e.g. a database change forcing a redeploy. */
  dependencies: string[];

  /** Actionable next steps for the operator. Never engineering instructions — this sprint plans nothing. */
  recommendations: string[];

  overallConfidence: ImpactConfidence;

  /**
   * True whenever the analysis rests on anything weaker than an exact identifier match — which is
   * most of the time. See this file's header: deterministic matching does not understand intent.
   */
  requiresHumanReview: boolean;

  /** Every conclusion, in order, so a human can audit the chain rather than trust a score. */
  reasoning: string[];

  /** Counts the dashboard renders without walking the sections. */
  summary: {
    affectedSections: number;
    totalFindings: number;
    highConfidenceFindings: number;
    affectedFeatures: number;
    affectedFiles: number;
    affectedTables: number;
  };
}

export const RISK_LEVEL_LABELS: Record<RiskLevel, string> = {
  low: 'Low',
  medium: 'Medium',
  high: 'High',
  critical: 'Critical',
};

export const COMPLEXITY_LEVEL_LABELS: Record<ComplexityLevel, string> = {
  very_small: 'Very Small',
  small: 'Small',
  medium: 'Medium',
  large: 'Large',
  very_large: 'Very Large',
};
