import type { ProjectBlueprint } from './types';

/**
 * Blueprint Engine — registry.
 *
 * The raw data. This is intentionally NOT exported from
 * app/lib/blueprints/index.ts — everything outside this module reads
 * blueprint data through blueprintEngine (engine.ts), never this array
 * directly, so the registry's storage shape can change later without
 * touching any consumer.
 *
 * Data is unchanged from Sprint 3/4 — same 9 blueprints, same fields,
 * same India-first payment guidance (Razorpay/UPI/PhonePe/Paytm/Cashfree,
 * no Stripe).
 */
export const PROJECT_BLUEPRINTS: ProjectBlueprint[] = [
  {
    id: 'blank-project',
    name: 'Blank Project',
    icon: '⭐',
    description: 'Start from a clean workspace with no assumptions.',
    category: 'General',
    productType: 'Unopinionated Workspace',
    recommendedStack: [],
    recommendedIntegrations: [],
    recommendedNextSteps: ['Describe what you want to build', 'Pick a stack as you go'],
    targetUsers: 'Anyone starting from scratch',
    defaultStatus: 'Planning',
    enabled: true,
  },
  {
    id: 'business-website',
    name: 'Business Website',
    icon: '🏪',
    description: 'Perfect for local businesses, corporate websites and landing pages.',
    category: 'Website',
    productType: 'Marketing / Service Website',
    recommendedStack: ['Next.js', 'Tailwind CSS', 'Supabase (optional)', 'WhatsApp CTA'],
    recommendedIntegrations: ['WhatsApp', 'Google Maps', 'Contact Form', 'SEO'],
    recommendedNextSteps: [
      'Create homepage',
      'Add services section',
      'Add contact section',
      'Add WhatsApp CTA',
      'Add SEO metadata',
    ],
    targetUsers: 'Local businesses and service providers',
    defaultStatus: 'Planning',
    enabled: true,
  },
  {
    id: 'localshop-india',
    name: 'LocalShop India',
    icon: '🛍️',
    description: 'A commerce storefront built for Indian MSMEs.',
    category: 'Commerce',
    productType: 'Shopify-like MSME ecommerce platform',
    recommendedStack: ['Next.js', 'Supabase', 'Tailwind CSS', 'Razorpay', 'UPI', 'WhatsApp'],
    recommendedIntegrations: [
      'Supabase Auth',
      'Product Catalog',
      'Orders',
      'Razorpay / UPI Payments',
      'WhatsApp Notifications',
      'Admin Dashboard',
    ],
    recommendedNextSteps: [
      'Define vendor onboarding',
      'Create product catalog',
      'Design storefront',
      'Add cart and checkout',
      'Plan order management',
      'Plan payments with Razorpay/UPI',
    ],
    targetUsers: 'Indian MSMEs and local shop owners',
    defaultStatus: 'Planning',
    enabled: true,
  },
  {
    id: 'shopify-app',
    name: 'Shopify App',
    icon: '🛒',
    description: 'Custom apps and extensions for Shopify stores.',
    category: 'Commerce',
    productType: 'Shopify App / Extension',
    recommendedStack: ['Next.js', 'Shopify App Bridge', 'Shopify Admin API', 'Webhooks'],
    recommendedIntegrations: ['Shopify OAuth', 'Shopify Webhooks', 'Shopify Billing API'],
    recommendedNextSteps: [
      'Register app with Shopify Partners',
      'Set up OAuth flow',
      'Define required webhooks',
      'Plan billing via Shopify Billing API',
    ],
    targetUsers: 'Shopify merchants and app developers',
    defaultStatus: 'Planning',
    enabled: true,
  },
  {
    id: 'ai-agent',
    name: 'AI Agent',
    icon: '🤖',
    description: 'An autonomous or assistant-style AI agent product.',
    category: 'AI',
    productType: 'AI Agent / Assistant',
    recommendedStack: ['MCP Servers', 'Tool Calling', 'Vector Knowledge Base', 'Agent Memory'],
    recommendedIntegrations: ['MCP Servers', 'Browser Automation', 'Knowledge Base', 'Memory Store'],
    recommendedNextSteps: [
      'Define the agent’s goal and tools',
      'Connect MCP servers',
      'Set up knowledge base',
      'Design memory and workflow steps',
    ],
    targetUsers: 'Teams building AI-driven automation',
    defaultStatus: 'Planning',
    enabled: true,
  },
  {
    id: 'saas-starter',
    name: 'SaaS Starter',
    icon: '🚀',
    description: 'A foundation for subscription-based software products.',
    category: 'SaaS',
    productType: 'Subscription SaaS Product',
    recommendedStack: ['Next.js', 'Supabase', 'Tailwind CSS', 'Razorpay', 'UPI', 'Cashfree'],
    recommendedIntegrations: ['Supabase Auth', 'Razorpay Subscriptions', 'UPI', 'Cashfree', 'Email Notifications'],
    recommendedNextSteps: [
      'Define pricing plans',
      'Set up authentication',
      'Plan billing with Razorpay/UPI/Cashfree',
      'Design onboarding flow',
    ],
    targetUsers: 'Teams building subscription software',
    defaultStatus: 'Planning',
    enabled: true,
  },
  {
    id: 'mobile-app',
    name: 'Mobile App',
    icon: '📱',
    description: 'A companion or standalone mobile application.',
    category: 'Mobile',
    productType: 'Mobile Application',
    recommendedStack: ['React Native', 'Expo'],
    recommendedIntegrations: ['Push Notifications', 'Supabase Auth'],
    recommendedNextSteps: ['Define core screens', 'Set up navigation', 'Plan app store release'],
    targetUsers: 'Teams building a mobile companion app',
    defaultStatus: 'Planning',
    enabled: true,
  },
  {
    id: 'marketing-website',
    name: 'Marketing Website',
    icon: '🌐',
    description: 'A marketing site focused on conversion and brand.',
    category: 'Website',
    productType: 'Marketing / Brand Website',
    recommendedStack: ['Next.js', 'Tailwind CSS'],
    recommendedIntegrations: ['SEO', 'Analytics', 'Contact Form'],
    recommendedNextSteps: ['Define brand sections', 'Add SEO metadata', 'Add analytics'],
    targetUsers: 'Marketing and brand teams',
    defaultStatus: 'Planning',
    enabled: true,
  },
  {
    id: 'nextjs-saas',
    name: 'Next.js SaaS',
    icon: '⚡',
    description: 'A Next.js-flavored foundation for SaaS products.',
    category: 'SaaS',
    productType: 'Next.js SaaS Product',
    recommendedStack: ['Next.js', 'Supabase', 'Tailwind CSS', 'Razorpay', 'UPI'],
    recommendedIntegrations: ['Supabase Auth', 'Razorpay', 'UPI', 'Email Notifications'],
    recommendedNextSteps: ['Set up authentication', 'Plan billing with Razorpay/UPI', 'Design dashboard'],
    targetUsers: 'Teams building a Next.js-based SaaS product',
    defaultStatus: 'Planning',
    enabled: true,
  },
];

/** id of the blueprint used when a project has none, or an unrecognized one. */
export const DEFAULT_BLUEPRINT_ID = 'blank-project';
