import type { ProjectBlueprint } from './types';

/**
 * Blueprint Engine — registry.
 *
 * The raw data. This is intentionally NOT exported from
 * app/lib/blueprints/index.ts — everything outside this module reads
 * blueprint data through blueprintEngine (engine.ts), never this array
 * directly, so the registry's storage shape can change later without
 * touching any consumer.
 *
 * Data is unchanged from Sprint 3/4 — same 9 blueprints, same fields,
 * same India-first payment guidance (Razorpay/UPI/PhonePe/Paytm/Cashfree,
 * no Stripe).
 *
 * Sprint 59 (Blueprint Foundation) gives this array a second role: it is now also the seed
 * data inserted into BuildersDB's `builders_blueprints` table (see
 * supabase/migrations/20260729100000_blueprint_foundation.sql — every field/value below is
 * duplicated there verbatim). This array remains `blueprintEngine`'s permanent fallback —
 * `engine.ts`'s `activeBlueprints` cache starts as this exact array and only ever swaps to
 * BuildersDB-sourced data after a successful `hydrateBlueprints()`, never removing this as the
 * safety net for an unconfigured/unreachable BuildersDB.
 */
export const PROJECT_BLUEPRINTS: ProjectBlueprint[] = [
  {
    id: 'blank-project',
    name: 'Blank Project',
    icon: '⭐',
    description: 'Start from a clean workspace with no assumptions.',
    category: 'General',
    productType: 'Unopinionated Workspace',
    recommendedStack: [],
    recommendedIntegrations: [],
    recommendedNextSteps: ['Describe what you want to build', 'Pick a stack as you go'],
    roadmap: [
      { key: 'requirements', title: 'Requirements', description: 'Describe what you want to build.' },
      { key: 'planning', title: 'Planning', description: 'Pick a stack and approach as you go.' },
      { key: 'deployment', title: 'Deployment', description: 'Deploy the project once it is ready.' },
    ],
    targetUsers: 'Anyone starting from scratch',
    defaultStatus: 'Planning',
    enabled: true,
  },
  {
    id: 'business-website',
    name: 'Business Website',
    icon: '🏪',
    description: 'Perfect for local businesses, corporate websites and landing pages.',
    category: 'Website',
    productType: 'Marketing / Service Website',
    recommendedStack: ['Next.js', 'Tailwind CSS', 'Supabase (optional)', 'WhatsApp CTA'],
    recommendedIntegrations: ['WhatsApp', 'Google Maps', 'Contact Form', 'SEO'],
    recommendedNextSteps: [
      'Create homepage',
      'Add services section',
      'Add contact section',
      'Add WhatsApp CTA',
      'Add SEO metadata',
    ],
    roadmap: [
      { key: 'requirements', title: 'Requirements', description: 'Define business requirements.' },
      { key: 'homepage', title: 'Homepage', description: 'Design and build the homepage.' },
      { key: 'navigation', title: 'Navigation', description: 'Set up site navigation and structure.' },
      { key: 'services', title: 'Services', description: 'Add a services section.' },
      { key: 'about', title: 'About', description: 'Add an About section.' },
      { key: 'contact', title: 'Contact', description: 'Add a contact section and form.' },
      { key: 'seo', title: 'SEO', description: 'Add SEO metadata.' },
      {
        key: 'responsive-design',
        title: 'Responsive Design',
        description: 'Ensure the site works on all screen sizes.',
      },
      { key: 'deployment', title: 'Deployment', description: 'Deploy the website.' },
    ],
    targetUsers: 'Local businesses and service providers',
    defaultStatus: 'Planning',
    enabled: true,
  },
  {
    id: 'localshop-india',
    name: 'LocalShop India',
    icon: '🛍️',
    description: 'A commerce storefront built for Indian MSMEs.',
    category: 'Commerce',
    productType: 'Shopify-like MSME ecommerce platform',
    recommendedStack: ['Next.js', 'Supabase', 'Tailwind CSS', 'Razorpay', 'UPI', 'WhatsApp'],
    recommendedIntegrations: [
      'Supabase Auth',
      'Product Catalog',
      'Orders',
      'Razorpay / UPI Payments',
      'WhatsApp Notifications',
      'Admin Dashboard',
    ],
    recommendedNextSteps: [
      'Define vendor onboarding',
      'Create product catalog',
      'Design storefront',
      'Add cart and checkout',
      'Plan order management',
      'Plan payments with Razorpay/UPI',
    ],
    roadmap: [
      { key: 'requirements', title: 'Requirements', description: 'Define business requirements.' },
      { key: 'vendor-model', title: 'Vendor Model', description: 'Define vendor onboarding and structure.' },
      { key: 'product-catalog', title: 'Product Catalog', description: 'Build the product catalog.' },
      { key: 'authentication', title: 'Authentication', description: 'Set up customer/vendor authentication.' },
      { key: 'shopping-cart', title: 'Shopping Cart', description: 'Add cart functionality.' },
      { key: 'checkout', title: 'Checkout', description: 'Build the checkout flow.' },
      {
        key: 'razorpay-upi-payments',
        title: 'Razorpay / UPI Payments',
        description: 'Integrate Razorpay and UPI payments.',
      },
      { key: 'order-management', title: 'Order Management', description: 'Plan order management and fulfillment.' },
      { key: 'notifications', title: 'Notifications', description: 'Add order and vendor notifications.' },
      { key: 'deployment', title: 'Deployment', description: 'Deploy the storefront.' },
    ],
    targetUsers: 'Indian MSMEs and local shop owners',
    defaultStatus: 'Planning',
    enabled: true,
  },
  {
    id: 'shopify-app',
    name: 'Shopify App',
    icon: '🛒',
    description: 'Custom apps and extensions for Shopify stores.',
    category: 'Commerce',
    productType: 'Shopify App / Extension',
    recommendedStack: ['Next.js', 'Shopify App Bridge', 'Shopify Admin API', 'Webhooks'],
    recommendedIntegrations: ['Shopify OAuth', 'Shopify Webhooks', 'Shopify Billing API'],
    recommendedNextSteps: [
      'Register app with Shopify Partners',
      'Set up OAuth flow',
      'Define required webhooks',
      'Plan billing via Shopify Billing API',
    ],
    roadmap: [
      { key: 'requirements', title: 'Requirements', description: 'Define business requirements.' },
      { key: 'app-structure', title: 'App Structure', description: 'Register the app and define its structure.' },
      { key: 'authentication', title: 'Authentication', description: 'Set up the Shopify OAuth flow.' },
      { key: 'polaris-ui', title: 'Polaris UI', description: 'Build the UI with Shopify Polaris.' },
      { key: 'app-bridge', title: 'App Bridge', description: 'Integrate Shopify App Bridge.' },
      { key: 'webhooks', title: 'Webhooks', description: 'Define required Shopify webhooks.' },
      { key: 'billing', title: 'Billing', description: 'Plan billing via the Shopify Billing API.' },
      { key: 'testing', title: 'Testing', description: 'Test the app against a development store.' },
      { key: 'deployment', title: 'Deployment', description: 'Submit and deploy the app.' },
    ],
    targetUsers: 'Shopify merchants and app developers',
    defaultStatus: 'Planning',
    enabled: true,
  },
  {
    id: 'ai-agent',
    name: 'AI Agent',
    icon: '🤖',
    description: 'An autonomous or assistant-style AI agent product.',
    category: 'AI',
    productType: 'AI Agent / Assistant',
    recommendedStack: ['MCP Servers', 'Tool Calling', 'Vector Knowledge Base', 'Agent Memory'],
    recommendedIntegrations: ['MCP Servers', 'Browser Automation', 'Knowledge Base', 'Memory Store'],
    recommendedNextSteps: [
      'Define the agent’s goal and tools',
      'Connect MCP servers',
      'Set up knowledge base',
      'Design memory and workflow steps',
    ],
    roadmap: [
      { key: 'requirements', title: 'Requirements', description: 'Define business requirements.' },
      { key: 'architecture', title: 'Architecture', description: "Define the agent's goal, tools, and architecture." },
      { key: 'memory', title: 'Memory', description: 'Design agent memory and state.' },
      { key: 'knowledge-base', title: 'Knowledge Base', description: 'Set up the knowledge base.' },
      { key: 'tool-calling', title: 'Tool Calling', description: 'Define and wire up tool calling.' },
      { key: 'mcp', title: 'MCP', description: 'Connect MCP servers.' },
      { key: 'browser-automation', title: 'Browser Automation', description: 'Set up browser automation, if needed.' },
      { key: 'testing', title: 'Testing', description: 'Test agent behavior end-to-end.' },
      { key: 'deployment', title: 'Deployment', description: 'Deploy the agent.' },
    ],
    targetUsers: 'Teams building AI-driven automation',
    defaultStatus: 'Planning',
    enabled: true,
  },
  {
    id: 'saas-starter',
    name: 'SaaS Starter',
    icon: '🚀',
    description: 'A foundation for subscription-based software products.',
    category: 'SaaS',
    productType: 'Subscription SaaS Product',
    recommendedStack: ['Next.js', 'Supabase', 'Tailwind CSS', 'Razorpay', 'UPI', 'Cashfree'],
    recommendedIntegrations: ['Supabase Auth', 'Razorpay Subscriptions', 'UPI', 'Cashfree', 'Email Notifications'],
    recommendedNextSteps: [
      'Define pricing plans',
      'Set up authentication',
      'Plan billing with Razorpay/UPI/Cashfree',
      'Design onboarding flow',
    ],
    roadmap: [
      { key: 'requirements', title: 'Requirements', description: 'Define business requirements.' },
      { key: 'pricing-plans', title: 'Pricing Plans', description: 'Define subscription pricing plans.' },
      { key: 'authentication', title: 'Authentication', description: 'Set up user authentication.' },
      {
        key: 'billing',
        title: 'Billing',
        description: 'Plan billing with Razorpay, UPI, or Cashfree.',
      },
      { key: 'onboarding', title: 'Onboarding', description: 'Design the onboarding flow.' },
      { key: 'testing', title: 'Testing', description: 'Test core flows end-to-end.' },
      { key: 'deployment', title: 'Deployment', description: 'Deploy the product.' },
    ],
    targetUsers: 'Teams building subscription software',
    defaultStatus: 'Planning',
    enabled: true,
  },
  {
    id: 'mobile-app',
    name: 'Mobile App',
    icon: '📱',
    description: 'A companion or standalone mobile application.',
    category: 'Mobile',
    productType: 'Mobile Application',
    recommendedStack: ['React Native', 'Expo'],
    recommendedIntegrations: ['Push Notifications', 'Supabase Auth'],
    recommendedNextSteps: ['Define core screens', 'Set up navigation', 'Plan app store release'],
    roadmap: [
      { key: 'requirements', title: 'Requirements', description: 'Define business requirements.' },
      { key: 'core-screens', title: 'Core Screens', description: 'Define the app’s core screens.' },
      { key: 'navigation', title: 'Navigation', description: 'Set up app navigation.' },
      { key: 'authentication', title: 'Authentication', description: 'Set up user authentication.' },
      { key: 'push-notifications', title: 'Push Notifications', description: 'Add push notifications.' },
      { key: 'app-store-release', title: 'App Store Release', description: 'Plan the app store release.' },
      { key: 'deployment', title: 'Deployment', description: 'Deploy/publish the app.' },
    ],
    targetUsers: 'Teams building a mobile companion app',
    defaultStatus: 'Planning',
    enabled: true,
  },
  {
    id: 'marketing-website',
    name: 'Marketing Website',
    icon: '🌐',
    description: 'A marketing site focused on conversion and brand.',
    category: 'Website',
    productType: 'Marketing / Brand Website',
    recommendedStack: ['Next.js', 'Tailwind CSS'],
    recommendedIntegrations: ['SEO', 'Analytics', 'Contact Form'],
    recommendedNextSteps: ['Define brand sections', 'Add SEO metadata', 'Add analytics'],
    roadmap: [
      { key: 'requirements', title: 'Requirements', description: 'Define business requirements.' },
      { key: 'brand-sections', title: 'Brand Sections', description: 'Define the site’s brand sections.' },
      { key: 'seo', title: 'SEO', description: 'Add SEO metadata.' },
      { key: 'analytics', title: 'Analytics', description: 'Add analytics tracking.' },
      { key: 'contact-form', title: 'Contact Form', description: 'Add a contact form.' },
      { key: 'deployment', title: 'Deployment', description: 'Deploy the website.' },
    ],
    targetUsers: 'Marketing and brand teams',
    defaultStatus: 'Planning',
    enabled: true,
  },
  {
    id: 'nextjs-saas',
    name: 'Next.js SaaS',
    icon: '⚡',
    description: 'A Next.js-flavored foundation for SaaS products.',
    category: 'SaaS',
    productType: 'Next.js SaaS Product',
    recommendedStack: ['Next.js', 'Supabase', 'Tailwind CSS', 'Razorpay', 'UPI'],
    recommendedIntegrations: ['Supabase Auth', 'Razorpay', 'UPI', 'Email Notifications'],
    recommendedNextSteps: ['Set up authentication', 'Plan billing with Razorpay/UPI', 'Design dashboard'],
    roadmap: [
      { key: 'requirements', title: 'Requirements', description: 'Define business requirements.' },
      { key: 'authentication', title: 'Authentication', description: 'Set up user authentication.' },
      { key: 'billing', title: 'Billing', description: 'Plan billing with Razorpay/UPI.' },
      { key: 'dashboard', title: 'Dashboard', description: 'Design the product dashboard.' },
      { key: 'testing', title: 'Testing', description: 'Test core flows end-to-end.' },
      { key: 'deployment', title: 'Deployment', description: 'Deploy the product.' },
    ],
    targetUsers: 'Teams building a Next.js-based SaaS product',
    defaultStatus: 'Planning',
    enabled: true,
  },
];

/** id of the blueprint used when a project has none, or an unrecognized one. */
export const DEFAULT_BLUEPRINT_ID = 'blank-project';
